# Generated by Django 3.2.8 on 2021-10-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoP', models.CharField(max_length=50)),
                ('apellidoM', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=60)),
                ('telefono', models.PositiveIntegerField()),
            ],
        ),
    ]
