# Generated by Django 3.2.8 on 2021-10-09 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellidoM',
            field=models.CharField(max_length=50, verbose_name='Apellido materno del usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellidoP',
            field=models.CharField(max_length=50, verbose_name='Apellido paterno del usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(verbose_name='Edad del usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Email del usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefono'),
        ),
    ]
